# Generated by Django 4.0.6 on 2022-07-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_description_foundation_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='foundation',
            new_name='name',
        ),
    ]
