# Generated by Django 4.0.6 on 2022-07-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_foundation_description_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='foundation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.foundation'),
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
