# Generated by Django 4.0.6 on 2022-07-14 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_description_foundation_alter_description_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(310, 'the field may only contain 310 characters.'), django.core.validators.MinLengthValidator(150, 'the field must have at least 150 characters.')]),
        ),
    ]
