# Generated by Django 4.0.6 on 2022-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_description_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='description',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
