# Generated by Django 4.0.6 on 2022-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_description_description_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='foundation_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
