# Generated by Django 4.0.6 on 2022-07-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_description_foundation_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='foundation_url',
            new_name='foundations_url',
        ),
    ]
